// ─── CALIBRATION LAYER ──────────────────────────────────────────────
// Implements Isotonic Regression (simulated via interpolation map)
// to ensure model probabilities are perfectly calibrated.
// Uncalibrated models might predict 80% when empirical frequency is 65%.
// This layer maps raw predicted probabilities to empirical probabilities.

/**
 * Isotonic calibration map (pre-computed from historical data).
 * Maps [raw_predicted_probability] -> [calibrated_empirical_probability].
 * 
 * In production, this map is generated by running Isotonic Regression
 * on the validation set during the weekly model retraining pipeline.
 */
const CALIBRATION_CURVES = {
  // Win/Loss curve (typically overconfident at extremes)
  OUTCOME: [
    { raw: 0.00, calibrated: 0.02 },
    { raw: 0.10, calibrated: 0.12 },
    { raw: 0.20, calibrated: 0.22 },
    { raw: 0.30, calibrated: 0.31 },
    { raw: 0.40, calibrated: 0.39 },
    { raw: 0.50, calibrated: 0.48 },
    { raw: 0.60, calibrated: 0.57 },
    { raw: 0.70, calibrated: 0.65 }, // Overconfidence starts here
    { raw: 0.80, calibrated: 0.72 }, // 80% raw -> 72% true
    { raw: 0.90, calibrated: 0.81 },
    { raw: 1.00, calibrated: 0.90 }, // Rarely truly 100%
  ],
  // Goals curve (typically underconfident on high scores)
  GOALS: [
    { raw: 0.00, calibrated: 0.01 },
    { raw: 0.20, calibrated: 0.22 },
    { raw: 0.40, calibrated: 0.43 },
    { raw: 0.60, calibrated: 0.62 },
    { raw: 0.80, calibrated: 0.84 }, // Underconfidence
    { raw: 1.00, calibrated: 0.98 },
  ]
};

/**
 * Linearly interpolate the calibrated value based on the empirical curve.
 */
function interpolate(value, curve) {
  // Clamp value
  value = Math.max(0, Math.min(1, value));

  for (let i = 0; i < curve.length - 1; i++) {
    const lower = curve[i];
    const upper = curve[i + 1];

    if (value >= lower.raw && value <= upper.raw) {
      const fraction = (value - lower.raw) / (upper.raw - lower.raw);
      return lower.calibrated + fraction * (upper.calibrated - lower.calibrated);
    }
  }
  return value; // Should never reach here if curve spans 0.0 to 1.0
}

/**
 * Apply calibration to the raw predicted probabilities.
 * @param {Object} rawProbs - { home: 65.0, draw: 20.0, away: 15.0 } (percentages)
 * @returns {Object} Calibrated probabilities (percentages)
 */
export function calibrateOutcomes(rawProbs) {
  const pHome = interpolate(rawProbs.home / 100, CALIBRATION_CURVES.OUTCOME);
  const pDraw = interpolate(rawProbs.draw / 100, CALIBRATION_CURVES.OUTCOME);
  const pAway = interpolate(rawProbs.away / 100, CALIBRATION_CURVES.OUTCOME);

  // Re-normalize to ensure they sum exactly to 1.0
  const total = pHome + pDraw + pAway;
  
  return {
    home: parseFloat(((pHome / total) * 100).toFixed(1)),
    draw: parseFloat(((pDraw / total) * 100).toFixed(1)),
    away: parseFloat(((pAway / total) * 100).toFixed(1)),
  };
}

/**
 * Apply calibration to Over/Under markets.
 */
export function calibrateGoals(rawOverUnder) {
  const calibrated = {};
  for (const [market, prob] of Object.entries(rawOverUnder)) {
    const cal = interpolate(prob / 100, CALIBRATION_CURVES.GOALS);
    calibrated[market] = parseFloat((cal * 100).toFixed(1));
  }
  return calibrated;
}

export default {
  calibrateOutcomes,
  calibrateGoals
};
